#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_a8f702_carrefour")]
	public partial class ContabilidadeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCTB_LANCAMENTO_ITEM(CTB_LANCAMENTO_ITEM instance);
    partial void UpdateCTB_LANCAMENTO_ITEM(CTB_LANCAMENTO_ITEM instance);
    partial void DeleteCTB_LANCAMENTO_ITEM(CTB_LANCAMENTO_ITEM instance);
    #endregion
		
		public ContabilidadeDataContext() : 
				base(global::Dao.Properties.Settings.Default.db_a8f702_carrefourConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public ContabilidadeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContabilidadeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContabilidadeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ContabilidadeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CTB_VISAO_CONTABIL> CTB_VISAO_CONTABILs
		{
			get
			{
				return this.GetTable<CTB_VISAO_CONTABIL>();
			}
		}
		
		public System.Data.Linq.Table<CTB_LANCAMENTO_ITEM> CTB_LANCAMENTO_ITEMs
		{
			get
			{
				return this.GetTable<CTB_LANCAMENTO_ITEM>();
			}
		}
		
		public System.Data.Linq.Table<CTB_BALANCETE> CTB_BALANCETEs
		{
			get
			{
				return this.GetTable<CTB_BALANCETE>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PROC_GERA_BALANCETE")]
		public int PROC_GERA_BALANCETE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DATA_INICIAL", DbType="DateTime")] System.Nullable<System.DateTime> dATA_INICIAL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DATA_FINAL", DbType="DateTime")] System.Nullable<System.DateTime> dATA_FINAL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MOSTRA_SEM_MOVIMENTO", DbType="Bit")] System.Nullable<bool> mOSTRA_SEM_MOVIMENTO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dATA_INICIAL, dATA_FINAL, mOSTRA_SEM_MOVIMENTO);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTB_VISAO_CONTABIL")]
	public partial class CTB_VISAO_CONTABIL
	{
		
		private string _VISAO_CONTABIL;
		
		private string _CLASSIFICACAO;
		
		private string _DESCR_CONTA;
		
		private string _NIVEL_CONTA;
		
		private string _NIVEL1;
		
		private string _NIVEL2;
		
		private string _NIVEL3;
		
		private string _NIVEL4;
		
		private string _NIVEL5;
		
		public CTB_VISAO_CONTABIL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VISAO_CONTABIL", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string VISAO_CONTABIL
		{
			get
			{
				return this._VISAO_CONTABIL;
			}
			set
			{
				if ((this._VISAO_CONTABIL != value))
				{
					this._VISAO_CONTABIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASSIFICACAO", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CLASSIFICACAO
		{
			get
			{
				return this._CLASSIFICACAO;
			}
			set
			{
				if ((this._CLASSIFICACAO != value))
				{
					this._CLASSIFICACAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCR_CONTA", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string DESCR_CONTA
		{
			get
			{
				return this._DESCR_CONTA;
			}
			set
			{
				if ((this._DESCR_CONTA != value))
				{
					this._DESCR_CONTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIVEL_CONTA", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string NIVEL_CONTA
		{
			get
			{
				return this._NIVEL_CONTA;
			}
			set
			{
				if ((this._NIVEL_CONTA != value))
				{
					this._NIVEL_CONTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIVEL1", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NIVEL1
		{
			get
			{
				return this._NIVEL1;
			}
			set
			{
				if ((this._NIVEL1 != value))
				{
					this._NIVEL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIVEL2", DbType="VarChar(20)")]
		public string NIVEL2
		{
			get
			{
				return this._NIVEL2;
			}
			set
			{
				if ((this._NIVEL2 != value))
				{
					this._NIVEL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIVEL3", DbType="VarChar(20)")]
		public string NIVEL3
		{
			get
			{
				return this._NIVEL3;
			}
			set
			{
				if ((this._NIVEL3 != value))
				{
					this._NIVEL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIVEL4", DbType="VarChar(20)")]
		public string NIVEL4
		{
			get
			{
				return this._NIVEL4;
			}
			set
			{
				if ((this._NIVEL4 != value))
				{
					this._NIVEL4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIVEL5", DbType="VarChar(20)")]
		public string NIVEL5
		{
			get
			{
				return this._NIVEL5;
			}
			set
			{
				if ((this._NIVEL5 != value))
				{
					this._NIVEL5 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTB_LANCAMENTO_ITEM")]
	public partial class CTB_LANCAMENTO_ITEM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CONTA_CONTABIL;
		
		private System.Nullable<decimal> _DEBITO;
		
		private System.Nullable<decimal> _CREDITO;
		
		private System.DateTime _DATA_LANCAMENTO;
		
		private string _HISTORICO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCONTA_CONTABILChanging(string value);
    partial void OnCONTA_CONTABILChanged();
    partial void OnDEBITOChanging(System.Nullable<decimal> value);
    partial void OnDEBITOChanged();
    partial void OnCREDITOChanging(System.Nullable<decimal> value);
    partial void OnCREDITOChanged();
    partial void OnDATA_LANCAMENTOChanging(System.DateTime value);
    partial void OnDATA_LANCAMENTOChanged();
    partial void OnHISTORICOChanging(string value);
    partial void OnHISTORICOChanged();
    #endregion
		
		public CTB_LANCAMENTO_ITEM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTA_CONTABIL", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CONTA_CONTABIL
		{
			get
			{
				return this._CONTA_CONTABIL;
			}
			set
			{
				if ((this._CONTA_CONTABIL != value))
				{
					this.OnCONTA_CONTABILChanging(value);
					this.SendPropertyChanging();
					this._CONTA_CONTABIL = value;
					this.SendPropertyChanged("CONTA_CONTABIL");
					this.OnCONTA_CONTABILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEBITO", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> DEBITO
		{
			get
			{
				return this._DEBITO;
			}
			set
			{
				if ((this._DEBITO != value))
				{
					this.OnDEBITOChanging(value);
					this.SendPropertyChanging();
					this._DEBITO = value;
					this.SendPropertyChanged("DEBITO");
					this.OnDEBITOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREDITO", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> CREDITO
		{
			get
			{
				return this._CREDITO;
			}
			set
			{
				if ((this._CREDITO != value))
				{
					this.OnCREDITOChanging(value);
					this.SendPropertyChanging();
					this._CREDITO = value;
					this.SendPropertyChanged("CREDITO");
					this.OnCREDITOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_LANCAMENTO", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime DATA_LANCAMENTO
		{
			get
			{
				return this._DATA_LANCAMENTO;
			}
			set
			{
				if ((this._DATA_LANCAMENTO != value))
				{
					this.OnDATA_LANCAMENTOChanging(value);
					this.SendPropertyChanging();
					this._DATA_LANCAMENTO = value;
					this.SendPropertyChanged("DATA_LANCAMENTO");
					this.OnDATA_LANCAMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HISTORICO", DbType="VarChar(250) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string HISTORICO
		{
			get
			{
				return this._HISTORICO;
			}
			set
			{
				if ((this._HISTORICO != value))
				{
					this.OnHISTORICOChanging(value);
					this.SendPropertyChanging();
					this._HISTORICO = value;
					this.SendPropertyChanged("HISTORICO");
					this.OnHISTORICOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTB_BALANCETE")]
	public partial class CTB_BALANCETE
	{
		
		private string _VISAO_CONTABIL;
		
		private string _CLASSIFICACAO;
		
		private string _DESCR_CONTA;
		
		private string _NIVEL_CONTA;
		
		private string _NIVEL1;
		
		private string _NIVEL2;
		
		private string _NIVEL3;
		
		private string _NIVEL4;
		
		private string _NIVEL5;
		
		private System.Nullable<decimal> _SALDO;
		
		private System.Nullable<decimal> _DEBITO;
		
		private System.Nullable<decimal> _CREDITO;
		
		private System.Nullable<decimal> _SALDO_FINAL;
		
		public CTB_BALANCETE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VISAO_CONTABIL", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string VISAO_CONTABIL
		{
			get
			{
				return this._VISAO_CONTABIL;
			}
			set
			{
				if ((this._VISAO_CONTABIL != value))
				{
					this._VISAO_CONTABIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLASSIFICACAO", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CLASSIFICACAO
		{
			get
			{
				return this._CLASSIFICACAO;
			}
			set
			{
				if ((this._CLASSIFICACAO != value))
				{
					this._CLASSIFICACAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCR_CONTA", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string DESCR_CONTA
		{
			get
			{
				return this._DESCR_CONTA;
			}
			set
			{
				if ((this._DESCR_CONTA != value))
				{
					this._DESCR_CONTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIVEL_CONTA", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string NIVEL_CONTA
		{
			get
			{
				return this._NIVEL_CONTA;
			}
			set
			{
				if ((this._NIVEL_CONTA != value))
				{
					this._NIVEL_CONTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIVEL1", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NIVEL1
		{
			get
			{
				return this._NIVEL1;
			}
			set
			{
				if ((this._NIVEL1 != value))
				{
					this._NIVEL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIVEL2", DbType="VarChar(20)")]
		public string NIVEL2
		{
			get
			{
				return this._NIVEL2;
			}
			set
			{
				if ((this._NIVEL2 != value))
				{
					this._NIVEL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIVEL3", DbType="VarChar(20)")]
		public string NIVEL3
		{
			get
			{
				return this._NIVEL3;
			}
			set
			{
				if ((this._NIVEL3 != value))
				{
					this._NIVEL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIVEL4", DbType="VarChar(20)")]
		public string NIVEL4
		{
			get
			{
				return this._NIVEL4;
			}
			set
			{
				if ((this._NIVEL4 != value))
				{
					this._NIVEL4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIVEL5", DbType="VarChar(20)")]
		public string NIVEL5
		{
			get
			{
				return this._NIVEL5;
			}
			set
			{
				if ((this._NIVEL5 != value))
				{
					this._NIVEL5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALDO", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> SALDO
		{
			get
			{
				return this._SALDO;
			}
			set
			{
				if ((this._SALDO != value))
				{
					this._SALDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEBITO", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> DEBITO
		{
			get
			{
				return this._DEBITO;
			}
			set
			{
				if ((this._DEBITO != value))
				{
					this._DEBITO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREDITO", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> CREDITO
		{
			get
			{
				return this._CREDITO;
			}
			set
			{
				if ((this._CREDITO != value))
				{
					this._CREDITO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALDO_FINAL", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> SALDO_FINAL
		{
			get
			{
				return this._SALDO_FINAL;
			}
			set
			{
				if ((this._SALDO_FINAL != value))
				{
					this._SALDO_FINAL = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
