<?xml version="1.0" encoding="utf-8"?><Database Name="db_a8f702_carrefour" Class="FaturamentoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SQL8001.site4now.net;Initial Catalog=db_a8f702_carrefour;User ID=db_a8f702_carrefour_admin" SettingsObjectName="Dao.Properties.Settings" SettingsPropertyName="db_a8f702_carrefourConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FATURAMENTO_DIARIO" Member="FATURAMENTO_DIARIOs">
    <Type Name="FATURAMENTO_DIARIO">
      <Column Name="GRUPO_PRODUTO" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="NATUREZA_SAIDA" Type="System.String" DbType="Char(7) NOT NULL" CanBeNull="false" />
      <Column Name="VALOR" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FATURAMENTO_MENSAL" Member="FATURAMENTO_MENSALs">
    <Type Name="FATURAMENTO_MENSAL">
      <Column Name="GRUPO_PRODUTO" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="VALOR" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </Type>
  </Table>
</Database>