#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_a8f702_carrefour")]
	public partial class FaturamentoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public FaturamentoDataContext() : 
				base(global::Dao.Properties.Settings.Default.db_a8f702_carrefourConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public FaturamentoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FaturamentoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FaturamentoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FaturamentoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FATURAMENTO_DIARIO> FATURAMENTO_DIARIOs
		{
			get
			{
				return this.GetTable<FATURAMENTO_DIARIO>();
			}
		}
		
		public System.Data.Linq.Table<FATURAMENTO_MENSAL> FATURAMENTO_MENSALs
		{
			get
			{
				return this.GetTable<FATURAMENTO_MENSAL>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FATURAMENTO_DIARIO")]
	public partial class FATURAMENTO_DIARIO
	{
		
		private string _GRUPO_PRODUTO;
		
		private string _NATUREZA_SAIDA;
		
		private System.Nullable<decimal> _VALOR;
		
		public FATURAMENTO_DIARIO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPO_PRODUTO", DbType="VarChar(25)")]
		public string GRUPO_PRODUTO
		{
			get
			{
				return this._GRUPO_PRODUTO;
			}
			set
			{
				if ((this._GRUPO_PRODUTO != value))
				{
					this._GRUPO_PRODUTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NATUREZA_SAIDA", DbType="Char(7) NOT NULL", CanBeNull=false)]
		public string NATUREZA_SAIDA
		{
			get
			{
				return this._NATUREZA_SAIDA;
			}
			set
			{
				if ((this._NATUREZA_SAIDA != value))
				{
					this._NATUREZA_SAIDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> VALOR
		{
			get
			{
				return this._VALOR;
			}
			set
			{
				if ((this._VALOR != value))
				{
					this._VALOR = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FATURAMENTO_MENSAL")]
	public partial class FATURAMENTO_MENSAL
	{
		
		private string _GRUPO_PRODUTO;
		
		private System.Nullable<decimal> _VALOR;
		
		public FATURAMENTO_MENSAL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPO_PRODUTO", DbType="VarChar(25)")]
		public string GRUPO_PRODUTO
		{
			get
			{
				return this._GRUPO_PRODUTO;
			}
			set
			{
				if ((this._GRUPO_PRODUTO != value))
				{
					this._GRUPO_PRODUTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> VALOR
		{
			get
			{
				return this._VALOR;
			}
			set
			{
				if ((this._VALOR != value))
				{
					this._VALOR = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
