#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_a8f702_carrefour")]
	public partial class FluxoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCTB_FLUXO(CTB_FLUXO instance);
    partial void UpdateCTB_FLUXO(CTB_FLUXO instance);
    partial void DeleteCTB_FLUXO(CTB_FLUXO instance);
    #endregion
		
		public FluxoDataContext() : 
				base(global::Dao.Properties.Settings.Default.db_a8f702_carrefourConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public FluxoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FluxoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FluxoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FluxoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CTB_FLUXO> CTB_FLUXOs
		{
			get
			{
				return this.GetTable<CTB_FLUXO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTB_FLUXO")]
	public partial class CTB_FLUXO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<System.DateTime> _DATA_LANCAMENTO;
		
		private string _DESCRICAO;
		
		private System.Nullable<decimal> _DEBITO;
		
		private System.Nullable<decimal> _CREDITO;
		
		private System.Nullable<decimal> _SALDO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDATA_LANCAMENTOChanging(System.Nullable<System.DateTime> value);
    partial void OnDATA_LANCAMENTOChanged();
    partial void OnDESCRICAOChanging(string value);
    partial void OnDESCRICAOChanged();
    partial void OnDEBITOChanging(System.Nullable<decimal> value);
    partial void OnDEBITOChanged();
    partial void OnCREDITOChanging(System.Nullable<decimal> value);
    partial void OnCREDITOChanged();
    partial void OnSALDOChanging(System.Nullable<decimal> value);
    partial void OnSALDOChanged();
    #endregion
		
		public CTB_FLUXO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_LANCAMENTO", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATA_LANCAMENTO
		{
			get
			{
				return this._DATA_LANCAMENTO;
			}
			set
			{
				if ((this._DATA_LANCAMENTO != value))
				{
					this.OnDATA_LANCAMENTOChanging(value);
					this.SendPropertyChanging();
					this._DATA_LANCAMENTO = value;
					this.SendPropertyChanged("DATA_LANCAMENTO");
					this.OnDATA_LANCAMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRICAO", DbType="VarChar(MAX)")]
		public string DESCRICAO
		{
			get
			{
				return this._DESCRICAO;
			}
			set
			{
				if ((this._DESCRICAO != value))
				{
					this.OnDESCRICAOChanging(value);
					this.SendPropertyChanging();
					this._DESCRICAO = value;
					this.SendPropertyChanged("DESCRICAO");
					this.OnDESCRICAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEBITO", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> DEBITO
		{
			get
			{
				return this._DEBITO;
			}
			set
			{
				if ((this._DEBITO != value))
				{
					this.OnDEBITOChanging(value);
					this.SendPropertyChanging();
					this._DEBITO = value;
					this.SendPropertyChanged("DEBITO");
					this.OnDEBITOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREDITO", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> CREDITO
		{
			get
			{
				return this._CREDITO;
			}
			set
			{
				if ((this._CREDITO != value))
				{
					this.OnCREDITOChanging(value);
					this.SendPropertyChanging();
					this._CREDITO = value;
					this.SendPropertyChanged("CREDITO");
					this.OnCREDITOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALDO", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> SALDO
		{
			get
			{
				return this._SALDO;
			}
			set
			{
				if ((this._SALDO != value))
				{
					this.OnSALDOChanging(value);
					this.SendPropertyChanging();
					this._SALDO = value;
					this.SendPropertyChanged("SALDO");
					this.OnSALDOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
